---
title: "PhenolicsDB MSMS spectra"
output:
  github_document:
    toc: true
    toc_depth: 2
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(tikzDefaultEngine = "xetex")
```

```{r setup, include=FALSE, eval=TRUE}
#library(PhenolicsDB)
library(tidyverse)
library(MS2extract)
```

```{r include=FALSE, eval=TRUE}
plot_MSspectra <- function(compound_names, MS2extract_object) {
  cp_name <- stringr::str_split(compound_names, "_")[[1]][1]
  cp_polarity <- stringr::str_split(compound_names, "_")[[1]][2]
  cp_CE <- stringr::str_split(compound_names, "_")[[1]][3]
  
  cat( stringr::str_glue("## {cp_name} {cp_polarity} polarity at {cp_CE} CE" ) )
  cat("\n")
  cat("\n")
  
  MSMS_plot <- MS2extract::plot_MS2spectra(MS2extract_object, compound_names)
  print(MSMS_plot)
  cat("\n")
  cat("\n")
}
```


```{r eval=TRUE, include=FALSE}
devtools::load_all()
neg_compound_names <- sort(names(neg_batch_mass_detected))
```


# Negative polarity


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results='asis', out.width="100%"}
for(cpname in neg_compound_names) {
  plot_MSspectra(compound_names = cpname, MS2extract_object = neg_batch_mass_detected)
}
```


# Positive polarity



```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results='asis'}
pos_compound_names <- sort(names(pos_batch_mass_detected))

for(cpname in pos_compound_names) {
  plot_MSspectra(compound_names = cpname, MS2extract_object = pos_batch_mass_detected)
}
```
